### ISSUE TITLE
Fix localization for Mac OSX

### ISSUE THREAD

**Issue by yupferris** [yupferris/fart-os#4]
Oh, the great horror! The recent fix for localization doesn't appear to work as described in the readme on OSX.

```
$ ASFLAGS=-DSUBJECT=\\"Ola\\" make test
clang -o pad pad.c
nasm -DSUBJECT=\Ola\ -o boot-raw.bin boot.asm
nasm: error: more than one input file specified
type `nasm -h' for help
make: *** [boot-raw.bin] Error 1
```

This works, however:

```
$ ASFLAGS=-DSUBJECT=\\\"Ola\\\" make
clang -o pad pad.c
nasm -DSUBJECT=\"Ola\" -o boot-raw.bin boot.asm
./pad boot-raw.bin boot.bin
```

And it still works with no customization as well:

```
$ make
clang -o pad pad.c
nasm  -o boot-raw.bin boot.asm
./pad boot-raw.bin boot.bin
```

Oh, the woes of using inferior operating systems. Are you able to test that the extra escaping still works for you, @kusma? If so, we can simply fix the documentation, and all will be right with the world again.

**Comment by kusma** [comment]
Actually, that was a typo on my behalf. I also need three slashes, so yeah. Sorry about that!

**Comment by yupferris** [comment]
np, thanks!
